name: Action Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKFLOW
                echo "${{github.token}}"


            - name: Checkout
              uses: actions/checkout@v2  #This is used to checkout the environment
            - name: List Files After Checkout
              run: |
                   pwd
                   ls -a

            - name: simple Javascript
              id: hello
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: develoment
            - name: Get the output Time
              run: echo "${{steps.hello.outputs.time}}"