name: Secrets workflow 

on: [push]
jobs:
    secrets-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Testing Secrets
              run: |
                echo "$DEVOPS"
              env:
                DEVOPS: ${{ secrets.SECRETS_TOKEN }}