name: Secrets workflow 

on: [push]
jobs:
    secrets-workflow:
        runs-on: ubuntu-latest
        env:
            DEVOPS: ${{ secrets.SECRETS_TOKEN }}
        steps:
            - name: Testing Secrets
              run: |
                echo "$DEVOPS"
              
            - name: conditional verification
              run: |
                if ["$DEVOPS" == "hello"]
                then
                    echo "Got our secrets"
                fi